base_mode_config: mode_config/base_mode_config.yaml
base_templates:
  - alive/base/ssh_alive_check.yaml
  - collect/base/ssh_version.yaml
  - collect/base/ssh_hostname.yaml
  - collect/base/ssh_serial_number.yaml
  - collect/base/ssh_ip_a.yaml
  - parse/base/version_extract.yaml
  - parse/base/hostname_extract.yaml
  - parse/base/serial_number_extract.yaml
  - transform/base/alive_check_transform.yaml