prompts:
  - "[\\r\\n]?[^\n]+(>|#) $"
  - "[\\r\\n]?[^\\n]+(]|#|>)[ ]?$"
err_prompts:
  - "(?i)error:"
  - "(?i)does not exist"
  - "command not found"
  - "No such file or directory"
init_commands:
  - "screen-length 0 temporary"
  - "screen-length disable"
  - "system-view"
save_commands:
  - "save"
first_chain:
  - "display current-configuration"
last_chain:
  - "display current-configuration"
auth_cmd: ""