name: snmpCdpProcess
indexPositions: [1,2]
classifierPositions: [0]
classifierToNameMap:
  "4": "ip"
  "6": "name"
  "7": "peer_interface"
classifierProcessors:
  "4": "IpPDU"
appendProcessors:
  - IosCdpIfindex
inputField: snmpCdp