name: snmpIpAddrEntryProcess
indexPositions: [1,2,3,4]
classifierPositions: [0]
classifierToNameMap:
  "1": "ip"
  "2": "ifindex"
  "3": "mask"
inputField: snmpIpAddrEntry

# 1.3.6.1.2.1.4.20.1.1.192.168.254.7 = IpAddress: 192.168.254.7
# 1.3.6.1.2.1.4.20.1.2.192.168.254.7 = INTEGER: 8190
# 1.3.6.1.2.1.4.20.1.3.192.168.254.7 = IpAddress: 255.255.255.0
# 1.3.6.1.2.1.4.20.1.4.192.168.254.7 = INTEGER: 1
# 1.3.6.1.2.1.4.20.1.5.192.168.254.7 = INTEGER: 65535
