devices:
  # - file_path: "2025-05-29-10.09.41-132.252.148.65-NJ-GL4F-G16U5-FW.RP.M9010.txt"
  - file_path: "2025-05-30-08.47.23-132.252.148.65-NJ-GL4F-G16U5-FW.RP.M9010.txt"
    mode: "SecPath"
    ipv4_area:
      - interface: "Route-Aggregation12.1051"
        name: "QXDCN"
        node_name: "NJ-GL4F-G16U5-FW.RP.M9010"
        force: true
    ipv4_stub:
      - port_name: "Route-Aggregation12.1052"
      - port_name: "Route-Aggregation12.1058"
      - port_name: "Route-Aggregation12.1054"
      - port_name: "Route-Aggregation12.1061"
      - port_name: "Route-Aggregation12.1053"
      - port_name: "Route-Aggregation12.1059"
      - port_name: "Route-Aggregation12.1055"
      - port_name: "Route-Aggregation12.1062"
      - port_name: "Route-Aggregation12.1057"
      - port_name: "Route-Aggregation12.1060"
      - port_name: "Route-Aggregation12.1063"
      - port_name: "Route-Aggregation12.1056"

  # - file_path: "2025-05-29-10.11.41-132.252.20.85-NJ-JiS-E16&17-FW-3.DMZ.F5000.txt"
  - file_path: "2025-05-30-08.49.06-132.252.20.85-NJ-JiS-E16&17-FW-3.DMZ.F5000.txt"
    mode: "SecPath"
    ipv4_area:
      - interface: "Reth5"
        name: "163"
        node_name: "NJ-JiS-E16&17-FW-3.DMZ.F5000"
        force: true
      - interface: "Reth4"
        name: "QXDCN"
        node_name: "NJ-JiS-E16&17-FW-3.DMZ.F5000"
        force: true
    ipv4_stub:
      - port_name: "Reth3"

  # - file_path: "2025-05-29-10.12.17-132.239.180.12-CZ-LY-FW-1.BD.F5000.txt"
  - file_path: "2025-05-30-08.49.40-132.239.180.12-CZ-LY-FW-1.BD.F5000.txt"
    mode: "SecPath"
    ipv4_area:
      - interface: "Route-Aggregation14.100"
        name: "QXDCN"
        node_name: "CZ-LY-FW-1.BD.F5000"
        force: true
    ipv4_stub:
      - port_name: "Route-Aggregation14.103"
      - port_name: "Route-Aggregation14.101"
      - port_name: "Route-Aggregation14.102"

  # - file_path: "2025-05-29-10.16.56-132.254.194.188-H3C-F5K-DMZ-仪征403.txt"
  - file_path: "2025-05-30-08.51.44-132.254.194.188-H3C-F5K-DMZ-仪征403.txt"
    mode: "SecPath"
    ipv4_area:
      - interface: "Route-Aggregation2.1203"
        name: "163"
        node_name: "CTY-YZ-JS-YZ-MTDD-01D04F403-J01_12-02U23-H3C-F5000-NFW"
        force: true
    ipv4_stub:
      - port_name: "Route-Aggregation2.1204"
  # - file_path: "2025-05-29-10.18.14-132.254.63.254-tyy-fw-M9010-吉山5号楼702.txt"
  # - file_path: "2025-05-30-08.52.49-132.254.63.254-tyy-fw-M9010-吉山5号楼702.txt"
  #   mode: "SecPath"
  - file_path: "2025-05-30-08.48.03-132.252.20.11-NJ-JiS-E24-FW-1.RP.Edu8000E.txt"
    mode: "Huawei"
    ipv4_area:
      - interface: "Eth-Trunk2.10"
        name: "QXDCN"
        node_name: "NJ-JiS-E24-FW-1.RP.Edu8000E"
        force: true
    ipv4_stub:
      - port_name: "Eth-Trunk2.12"
      - port_name: "Eth-Trunk2.16"
      - port_name: "Eth-Trunk2.19"
      - port_name: "Eth-Trunk2.15"
      - port_name: "Eth-Trunk2.20"
      - port_name: "Eth-Trunk2.22"
      - port_name: "Eth-Trunk2.11"
      - port_name: "Eth-Trunk2.14"
      - port_name: "Eth-Trunk2.17"
      - port_name: "Eth-Trunk2.18"
      - port_name: "Eth-Trunk2.13"
      - port_name: "Eth-Trunk2.21"

  - file_path: "2025-05-30-08.48.37-132.252.20.83-NJ-JiS-E19-FW-1.DMZ.DP1000.txt"
    mode: "Dptech"
    ipv4_area:
      - interface: "bond11"
        name: "DCN"
        node_name: "NJ-JiS-E19-FW-1.DMZ.DP1000"
        force: true
    ipv4_stub:
      - port_name: "tunnel_ssl0"
      - port_name: "meth0_9"

  - file_path: "2025-05-30-08.50.14-132.254.194.222-DP1000-容灾备份-仪征403.txt"
    mode: "Dptech"
    ipv4_area:
      - interface: "vlan-if1208"
        name: "Untrust"
        node_name: "CTY-YZ-JS-YZ-MTDD-01D04F403-A13-06U19-DP-FW1000-NFW"
        force: true
    ipv4_stub:
      - port_name: "vlan-if1209"

  - file_path: "2025-05-30-08.50.44-132.254.194.147-DP1000-虚机资源池-仪征403.txt"
    mode: "Dptech"
    ipv4_area:
      - interface: "vlan-if4001"
        name: "Untrust"
        node_name: "CTY-YZ-JS-YZ-MTDD-01D04F403-J02_06-07U16-DP-FW1000-NFW"
        force: true
    ipv4_stub:
      - port_name: "vlan-if4002"

  - file_path: "2025-05-30-08.51.12-132.254.160.136-C8U31-FW-1.DCN.Edu1000E-仪征303.txt"
    mode: "Huawei"
    ipv4_area:
      - interface: "Eth-Trunk21.101"
        name: "QXDCN"
        node_name: "YZ-YiZ-C8U31-FW-1.DCN.Edu1000E"
        force: true
    ipv4_stub:
      - port_name: "Eth-Trunk21.102"
      - port_name: "Eth-Trunk21.104"
      - port_name: "Eth-Trunk21.103"
      - port_name: "Eth-Trunk21.105"

  # - file_path: "2025-05-30-08.52.17-132.254.194.190-DP1000-DMZ-仪征403.txt"
  #   mode: "Dptech"
  #   ipv4_area:
  #     - interface: "gige0_7"
  #       name: ""
  #       node_name: "CTY-YZ-JS-YZ-MTDD-01D04F403-J01_12-02U31-DP-FW1000-NFW"
  #       force: true
  #   ipv4_stub:
  #     - port_name: "bond2.1202"
  #     - port_name: "bond2.1201"

    # ipv4_area:
    #   - interface: "Route-Aggregation2.1203"
    #     name: "163"
    #     node_name: "JSJS-702-I04-CFW-M9010-20U03"
    #     force: true
  # - host: "172.32.1.221"
  #   username: "admin"
  #   password: "!@AsiaLink@2020"
  #   port: 22
  #   mode: "SecPath"
  #   telnet: false
  #   ipv4_area:
  #     - interface: "GigabitEthernet2/0"
  #       name: "Internet"
  #       node_name: "H3CNM"
  #       force: true
  # - host: "172.32.1.7"
  #   username: "admin"
  #   password: "admin@123"
  #   authPass: "admin@123"
  #   port: 22
  #   mode: "IOS"
  #   telnet: false
  # - host: "172.32.1.2"
  #   username: "admin"
  #   password: "admin@123"
  #   authPass: "admin@123"
  #   port: 22
  #   mode: "IOS"
  #   telnet: false
  # - host: "172.32.1.10"
  #   username: "admin"
  #   password: "admin@123"
  #   authPass: "admin@123"
  #   port: 22
  #   mode: "IOS"
  #   telnet: false
  # - host: "172.32.1.11"
  #   username: "admin"
  #   password: "admin@123"
  #   authPass: "admin@123"
  #   port: 22
  #   mode: "IOS"
  #   telnet: false
  # - host: "172.32.1.12"
  #   username: "admin"
  #   password: "admin@123"
  #   authPass: "admin@123"
  #   port: 22
  #   mode: "IOS"
  #   telnet: false
  # - host: "172.32.1.25"
  #   username: "admin"
  #   password: "admin@123"
  #   authPass: "admin@123"
  #   port: 22
  #   mode: "IOS"
  #   telnet: false
  # - host: "172.32.1.26"
  #   username: "admin"
  #   password: "admin@123"
  #   authPass: "admin@123"
  #   port: 22
  #   mode: "IOS"
  #   telnet: false
  # - host: "172.32.1.8"
  #   username: "admin"
  #   password: "admin@123"
  #   authPass: "admin@123"
  #   port: 22
  #   mode: "FortiGate"
  #   telnet: false
  #   token: "r7Hnnfgym6NqNQmxGHmrxnnf0d1Qdb"


nodemap:
  name: "H3CNM"
  force: true
  task_id: 1
config_file_path: "."
policy:
  source: "25.221.1.22/24"
  destination: "8.8.8.8/32"
  ticketNumber: HQWLTK20250327001
  subTicket: "1"
  service:
    protocol: "tcp"
    port: "80"
  snat: "26.221.1.222"
# policy:
#   source: "0.0.0.0/0"
#   destination: "26.221.1.23"
#   realIp: 25.221.1.23
#   realPort: 80
#   ticketNumber: HQWLTK20250327001
#   subTicket: "1"
#   service:
#     protocol: "tcp"
#     port: "80"
